# Generated by Django 4.1 on 2022-08-23 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("rooms", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "timestampedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.timestampedmodel",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
            ],
            options={
                "abstract": False,
            },
            bases=("core.timestampedmodel",),
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.ManyToManyField(to="rooms.roomtype"),
        ),
    ]
