# Generated by Django 4.1 on 2022-08-23 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("rooms", "0003_roomtype_room_room_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "timestampedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.timestampedmodel",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
            ],
            options={
                "abstract": False,
            },
            bases=("core.timestampedmodel",),
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "timestampedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.timestampedmodel",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
            ],
            options={
                "abstract": False,
            },
            bases=("core.timestampedmodel",),
        ),
        migrations.CreateModel(
            name="HouseRule",
            fields=[
                (
                    "timestampedmodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.timestampedmodel",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
            ],
            options={
                "abstract": False,
            },
            bases=("core.timestampedmodel",),
        ),
        migrations.RemoveField(
            model_name="room",
            name="room_type",
        ),
        migrations.AddField(
            model_name="room",
            name="amenities",
            field=models.ManyToManyField(to="rooms.amenity"),
        ),
        migrations.AddField(
            model_name="room",
            name="facilities",
            field=models.ManyToManyField(to="rooms.facility"),
        ),
        migrations.AddField(
            model_name="room",
            name="house_rules",
            field=models.ManyToManyField(to="rooms.houserule"),
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rooms.roomtype",
            ),
        ),
    ]
